viewAllparam = {...
    {'doMaps', 'Orientation map'},...
    {'doPhases', 'Phase map'},...
    {'doCI', 'Confidence index map'},...
    {'doIQ', 'Image quality map'},...
    {'doGrains', 'Information about grains'},...
    {'doSizes', 'Information about grain sizes'}...
};

disp
